### ISSUE TITLE
Error while compiling using make 

### ISSUE THREAD

**Issue by nk-dev0** [martinkersner/train-DeepLab#11]
I'm following the installation guide, and after I do "make all" I get the following error, which I suspect is from some issue with matio, although it is properly installed and I can access it via dpkg:

[ 88%] Building CXX object tools/CMakeFiles/caffe.bin.dir/caffe.cpp.o
Linking CXX executable caffe
../lib/libcaffe.a(blob.cpp.o): In function `caffe::Blob<float>::FromMat(char const*)':
blob.cpp:(.text._ZN5caffe4BlobIfE7FromMatEPKc[_ZN5caffe4BlobIfE7FromMatEPKc]+0x3d): undefined reference to`Mat_Open'
blob.cpp:(.text._ZN5caffe4BlobIfE7FromMatEPKc[_ZN5caffe4BlobIfE7FromMatEPKc]+0x117): undefined reference to `Mat_VarReadInfo'
blob.cpp:(.text._ZN5caffe4BlobIfE7FromMatEPKc[_ZN5caffe4BlobIfE7FromMatEPKc]+0x477): undefined reference to`Mat_VarReadDataLinear'
blob.cpp:(.text._ZN5caffe4BlobIfE7FromMatEPKc[_ZN5caffe4BlobIfE7FromMatEPKc]+0x548): undefined reference to `Mat_VarFree'
blob.cpp:(.text._ZN5caffe4BlobIfE7FromMatEPKc[_ZN5caffe4BlobIfE7FromMatEPKc]+0x55e): undefined reference to`Mat_VarReadInfo'
blob.cpp:(.text._ZN5caffe4BlobIfE7FromMatEPKc[_ZN5caffe4BlobIfE7FromMatEPKc]+0x6b0): undefined reference to `Mat_VarReadDataLinear'
blob.cpp:(.text._ZN5caffe4BlobIfE7FromMatEPKc[_ZN5caffe4BlobIfE7FromMatEPKc]+0x781): undefined reference to`Mat_VarFree'
blob.cpp:(.text._ZN5caffe4BlobIfE7FromMatEPKc[_ZN5caffe4BlobIfE7FromMatEPKc]+0x790): undefined reference to `Mat_Close'

Have you come across this error, and if so how did you get around it? Thanks.

**Comment by xtudbxk** [comment]
Any one looks for the solution jus visits https://github.com/TheLegendAli/DeepLab-Context2/issues/1, I solve this problem by the way.
