### ISSUE TITLE
Problem with mat2png.py

### ISSUE THREAD

**Issue by srika91** [martinkersner/train-DeepLab#2]
Hello,

I am using python 2.7.When i tried to run mat2png.py,it shows, 

```
KeyError: 'GTcls' and it is right as the function mat2png_hariharan in utils.py,is not assigning the key to the output.I tried may[key]=loadmat....,but still mat[key].Segmentation throws error.Any thoughts will be useful
```

**Comment by martinkersner** [comment]
Hi!

What dataset are you using?

Martin

**Comment by srika91** [comment]
I am using the training/validation data from [here](http://host.robots.ox.ac.uk/pascal/VOC/voc2010/index.html)

After extracting it I will get the trainval folder containing mat files.I want to convert those mat files to png files for which i am using your code mat2png.py. When I read one of the files I am getting a dictionary as below,

{'**version**': '1.0', '**globals**': [], '**header**': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Thu Jun 26 20:46:56 2014', 'LabelMap': array([[454, 454, 454, ..., 454, 454, 454],
       [454, 454, 454, ..., 454, 454, 454],
       [454, 454, 454, ..., 454, 454, 454],
       ..., 
       [431, 431, 431, ..., 273, 273, 273],
       [431, 431, 431, ..., 273, 273, 273],
       [431, 431, 431, ..., 273, 273, 273]], dtype=uint16)}

Now how to store the 'LabelMap' values as a png file with single channel.I am trying FCNN before going to deeplab which requires labels as single channel.

With what I have seen label files like .png files are single channel yet coloured,bcz of alpha channel,i could not  understand it?

**Comment by martinkersner** [comment]
I am not sure about PASCAL VOC 2010, but 2012 does not contain ground truth labels stored in  _mat_ files. PASCAL VOC 2012 contains more images, so maybe you should consider using that dataset.

In my opinion, FCNN also requires single channel ground truth labels.

If you want to use _mat2png.py_ for PASCAL VOC 2010, you need to replace _mat2png_hariharan_ with _load_mat_ defined in _utils.py_.

Cheers,

Martin

**Comment by srika91** [comment]
Thank you martin.I will try that as well.I ended up writing similar to  load_mat using scipy.io.loadmat
