### ISSUE TITLE
MIT or Apache v2 license?

### ISSUE THREAD

**Issue by ahundt** [martinkersner/train-DeepLab#23]
any chance you could add a license to this project?

Suggestions:
 - [MIT](https://tldrlegal.com/license/mit-license#fulltext)
    - about MIT: https://tldrlegal.com/license/mit-license
 - [Apache v2](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)#fulltext)
    - about Apache v2: https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

**Comment by martinkersner** [comment]
Hi!

Sure, I can.

But I am wondering how it will help/serve you?

Cheers,
Martin

**Comment by ahundt** [comment]
I'm hoping to adapt some of the dataset conversion code for pascal voc + keras and contribute it to keras-contrib:
https://github.com/farizrahman4u/keras-contrib
https://github.com/fchollet/keras

**Comment by ahundt** [comment]
So for that the MIT license would be ideal, otherwise they won't accept the pull request bc of licensing rules. :-)

**Comment by ahundt** [comment]
If that sounds ok to you & you can update the repo I'll work on that, and of course I'd put you in as an author in the header!

**Comment by martinkersner** [comment]
I have never had to dealt with licences, so I am not sure if I can actually put MIT license to this. Original DeepLab (which is linked as submodule) has [modified](https://bitbucket.org/deeplab/deeplab-public/src/26b6af817e4676f6409aa0d609096b31ff72917d/LICENSE?at=master&fileviewer=file-view-default) caffe licence which is BSD 2-Clause.

Do you think it is okay?

**Comment by ahundt** [comment]
yeah that should be fine, difference is minor

**Comment by martinkersner** [comment]
Ok! I added [MIT license](https://github.com/martinkersner/train-DeepLab/commit/509419a8b44dc0689d24184c7ffc24c81bce3078).

**Comment by ahundt** [comment]
Awesome, thanks!
