### ISSUE TITLE
How to generate the label image?

### ISSUE THREAD

**Issue by fengjunlv** [martinkersner/train-DeepLab#4]
Hi Martin, I found your tutorial very help and I am following it to train a model.   A quick question: do you have code snippet to generate the label image, like this one in your tutorial?  Thanks.

https://camo.githubusercontent.com/4df6f507fe1ec20b526af294eeadc482e0f4bf1e/687474703a2f2f692e696d6775722e636f6d2f6e35507a765a552e706e673f31

**Comment by martinkersner** [comment]
Hi @fengjunlv!

You can use [deeplab.py](https://github.com/martinkersner/train-DeepLab/blob/master/deeplab.py). Run it as 

``` bash
python deeplab.py GPU_ID NET MODEL IMAGE
```

Explanation of parameters is given in [help function](https://github.com/martinkersner/train-DeepLab/blob/master/deeplab.py#L95-L101).

Cheers,

Martin

**Comment by fengjunlv** [comment]
Awesome, it worked!!! Thanks a lot. 

Now there is another question: To run this script, I stopped the training process to get enough GPU memory.  Is there a way to resume the training?

**Comment by martinkersner** [comment]
Well, there are two ways. 

You can either change this [line](https://github.com/martinkersner/train-DeepLab/blob/master/run_pascal_strong.sh#L48) and put there your latest _caffemodel_, but in this case training starts from the beginning (it does not remember training parameters like iteration or learning rate).

Or you can do the similar resume as described [here](https://github.com/martinkersner/train-CRF-RNN/issues/11) in the last comment.

**Comment by fengjunlv** [comment]
I will give it a try.  Thanks, Martin.

**Comment by hypercost** [comment]
Hi @martinkersner, 
Which network definetion file should I use, such as DeepLabFOV? deploy21.prototxt?

If I use other model like DeepLabv2-VGG16 to predict image, I need write a deploy.prototxt ro run deeplab.py?
