### ISSUE TITLE
How to run deeplab.py?

### ISSUE THREAD

**Issue by koizora223** [martinkersner/train-DeepLab#5]
I want to run deeplab.py to show the result image. And I use  model 'vgg16_20M.caffemodel ' or 'train2_iter_8000.caffemodel' (download from the DeepLab models)and net 'deploy21.prototxt' in your project.But there is an error:
F0705 22:14:09.639734 19135 layer.hpp:378] Check failed: ExactNumTopBlobs() == top.size() (2 vs. 3) MEMORY_DATA Layer produces 2 top blob(s) as output.
Did I use the wrong deploy.prototxt or model?

**Comment by martinkersner** [comment]
Hi @koizora223,

If you want get only segmentation result you shouldn't use _vgg16_20M.caffemodel_ because it is just init model. The problem you are facing is probably because you don't use my modified caffe version. MEMORY_DATA Layer was changed and produces 3 outputs, instead of only 2. You have to clone repository with _--recursive_ parameter  and use caffe from _code_ directory.

Cheers,

Martin

**Comment by koizora223** [comment]
Hi @martinkersner 
Thanks for your answer! And I have solved the previous problem. But when I use the trained model 'train2_iter_8000.caffemodel' and deploy.prototext to run deeplab.py,I got another problem.My segment
results is all zeros.And I found one layer not initialized:
I0708 16:17:19.336496 27913 net.cpp:740] Target layer fc8_exper/voc12 not initialized.

I have checked net.cpp ,and I got layer_init_flag[i]==0,which should be 1.

Cheers,
Chen

**Comment by martinkersner** [comment]
In training prototxt there is layer definition

```
layers {
  bottom: "fc7"
  top: "fc8_${EXP}"
  name: "fc8_${EXP}"
  ...
```

which contains variable in layer name which was propagated from [training script](https://github.com/martinkersner/train-DeepLab/blob/master/run_pascal_strong.sh#L8). Therefore, this name can differ depending on path to dataset. You should check real name of that layer.

Hope that helps.

**Comment by koizora223** [comment]
Thanks a lot. It works!

Cheers.

**Comment by joestrummer82** [comment]
Hello,

just right now, i have the same issue, the layer definitions is called somehow because it was propagated from training script. But the error in due to initialization of target layer just pop up (not initialized). 

How to solve it?

Thanks in Advance

**Comment by RogerShaw** [comment]
Hi! @martinkersner i git clone your deeplab code. However, the code file is empty! How can i get the modified caffe code? i got the same question : Check failed: ExactNumTopBlobs() == top.size() (2 vs. 3) MEMORY_DATA Layer produces 2 top blob(s) as output.
