### ISSUE TITLE
Wrong prediction results?

### ISSUE THREAD

**Issue by koizora223** [martinkersner/train-DeepLab#7]
Hi @martinkersner 
I run deeplab.py using the downloaded official caffemodel(train2_iter_8000.caffemodel). But I get wrong results.The object seems to locate in the wrong position.  I have checked the output of each layer and found the output of fully connected layer fc6  incorrect. There are my results.Please give me some advices.Thanks!!
![c-label](https://cloud.githubusercontent.com/assets/13740440/17583542/162a6e84-5fe4-11e6-97d6-ddf0f3d242a8.png)

![a-label](https://cloud.githubusercontent.com/assets/13740440/17583453/b61642e8-5fe3-11e6-81b2-2e16780cd5c3.png)

Chen

**Comment by martinkersner** [comment]
Hi @koizora223,

What do you mean by "found [that] the output of fully connected layer fc6 [is] incorrect"? How did you find it out?

Cheers,
Martin

**Comment by koizora223** [comment]
Hi @martinkersner 
I have showed the output of  'pool5a' and ' fc6' layer using the code below in segmenter.py.
    feat = self.blobs['pool5a'].data[0, :21]
    vis_square(feat)
    feat = self.blobs['fc6'].data[0, :21]
    vis_square(feat)
And I got the following results:The coarse plane output from pooling layer(row2,col1) is at the right position,but wrong after fc6 layer(row1,col 1). The final prediction result is at the wrong position as the second image. What cause this?
![figure_0](https://cloud.githubusercontent.com/assets/13740440/17586138/69e4fafe-5ff2-11e6-87df-0a197b3a1135.jpg)
![figure_1](https://cloud.githubusercontent.com/assets/13740440/17586146/70625336-5ff2-11e6-9b51-07aebcb279ff.jpg)

Thanks,
Chen

**Comment by martinkersner** [comment]
@koizora223 I am sorry, but I don't know.

**Comment by koizora223** [comment]
Hi @martinkersner 
It is resovled by just compiling without cuDNN enabled.Thanks all the same!
And I have another question .Do you use cuDNN for training?

Cheers!

**Comment by martinkersner** [comment]
@koizora223 Great! I haven't used cuDNN for either training or testing.
